import type { ListingRecord, ResolvedLocation, SafetyRecord } from "@nhalo/types";

const now = "2026-03-22T00:00:00.000Z";

export const MOCK_LOCATIONS: Record<string, ResolvedLocation> = {
  "city:southfield, mi": {
    locationType: "city",
    locationValue: "Southfield, MI",
    center: { lat: 42.4734, lng: -83.2219 },
    city: "Southfield",
    state: "MI",
    postalCode: "48075"
  },
  "city:royal oak, mi": {
    locationType: "city",
    locationValue: "Royal Oak, MI",
    center: { lat: 42.4895, lng: -83.1446 },
    city: "Royal Oak",
    state: "MI",
    postalCode: "48067"
  },
  "city:novi, mi": {
    locationType: "city",
    locationValue: "Novi, MI",
    center: { lat: 42.4806, lng: -83.4755 },
    city: "Novi",
    state: "MI",
    postalCode: "48375"
  },
  "city:austin, tx": {
    locationType: "city",
    locationValue: "Austin, TX",
    center: { lat: 30.2672, lng: -97.7431 },
    city: "Austin",
    state: "TX",
    postalCode: "78701"
  },
  "zip:48075": {
    locationType: "zip",
    locationValue: "48075",
    center: { lat: 42.4841, lng: -83.2542 },
    city: "Southfield",
    state: "MI",
    postalCode: "48075"
  },
  "zip:78704": {
    locationType: "zip",
    locationValue: "78704",
    center: { lat: 30.2444, lng: -97.7659 },
    city: "Austin",
    state: "TX",
    postalCode: "78704"
  }
};

export const MOCK_LISTINGS: ListingRecord[] = [
  {
    id: "sf-001",
    provider: "mock-mls",
    address: "28510 Pierce St",
    city: "Southfield",
    state: "MI",
    zipCode: "48076",
    coordinates: { lat: 42.5004, lng: -83.2208 },
    propertyType: "single_family",
    price: 349000,
    sqft: 2140,
    bedrooms: 4,
    bathrooms: 2.5,
    lotSqft: 9147,
    sourceUrl: "https://example.com/listings/sf-001",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-mls" }
  },
  {
    id: "sf-002",
    provider: "mock-mls",
    address: "22841 Bell Rd",
    city: "Southfield",
    state: "MI",
    zipCode: "48034",
    coordinates: { lat: 42.4645, lng: -83.2651 },
    propertyType: "single_family",
    price: 412000,
    sqft: 2560,
    bedrooms: 4,
    bathrooms: 3,
    lotSqft: 11220,
    sourceUrl: "https://example.com/listings/sf-002",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-mls" }
  },
  {
    id: "sf-003",
    provider: "mock-redfin",
    address: "24655 Evergreen Rd Unit 5",
    city: "Southfield",
    state: "MI",
    zipCode: "48075",
    coordinates: { lat: 42.4746, lng: -83.2453 },
    propertyType: "condo",
    price: 229000,
    sqft: 1585,
    bedrooms: 3,
    bathrooms: 2,
    lotSqft: null,
    sourceUrl: "https://example.com/listings/sf-003",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-redfin" }
  },
  {
    id: "sf-004",
    provider: "mock-redfin",
    address: "29750 Fairfax St",
    city: "Southfield",
    state: "MI",
    zipCode: "48076",
    coordinates: { lat: 42.5199, lng: -83.2345 },
    propertyType: "single_family",
    price: 299000,
    sqft: 1890,
    bedrooms: 3,
    bathrooms: 2,
    lotSqft: 8276,
    sourceUrl: "https://example.com/listings/sf-004",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-redfin" }
  },
  {
    id: "sf-005",
    provider: "mock-realtor",
    address: "20250 Magnolia Pkwy",
    city: "Southfield",
    state: "MI",
    zipCode: "48075",
    coordinates: { lat: 42.4708, lng: -83.1992 },
    propertyType: "townhome",
    price: 319000,
    sqft: 1960,
    bedrooms: 3,
    bathrooms: 2.5,
    lotSqft: 2613,
    sourceUrl: "https://example.com/listings/sf-005",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-realtor" }
  },
  {
    id: "sf-006",
    provider: "mock-realtor",
    address: "15410 George Washington Dr",
    city: "Southfield",
    state: "MI",
    zipCode: "48075",
    coordinates: { lat: 42.495, lng: -83.2112 },
    propertyType: "single_family",
    price: 438000,
    sqft: 2840,
    bedrooms: 4,
    bathrooms: 3,
    lotSqft: 12632,
    sourceUrl: "https://example.com/listings/sf-006",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-realtor" }
  },
  {
    id: "oak-001",
    provider: "mock-mls",
    address: "22111 Republic Ave",
    city: "Oak Park",
    state: "MI",
    zipCode: "48237",
    coordinates: { lat: 42.4637, lng: -83.1861 },
    propertyType: "single_family",
    price: 274000,
    sqft: 1710,
    bedrooms: 3,
    bathrooms: 2,
    lotSqft: 6098,
    sourceUrl: "https://example.com/listings/oak-001",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-mls" }
  },
  {
    id: "oak-002",
    provider: "mock-redfin",
    address: "13600 Dartmouth St",
    city: "Oak Park",
    state: "MI",
    zipCode: "48237",
    coordinates: { lat: 42.4662, lng: -83.1758 },
    propertyType: "single_family",
    price: 312000,
    sqft: 2050,
    bedrooms: 4,
    bathrooms: 2,
    lotSqft: 7405,
    sourceUrl: "https://example.com/listings/oak-002",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-redfin" }
  },
  {
    id: "ro-001",
    provider: "mock-realtor",
    address: "2207 N Vermont Ave",
    city: "Royal Oak",
    state: "MI",
    zipCode: "48073",
    coordinates: { lat: 42.5121, lng: -83.1314 },
    propertyType: "single_family",
    price: 459000,
    sqft: 2175,
    bedrooms: 4,
    bathrooms: 2.5,
    lotSqft: 6534,
    sourceUrl: "https://example.com/listings/ro-001",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-realtor" }
  },
  {
    id: "lh-001",
    provider: "mock-mls",
    address: "27412 Southfield Rd",
    city: "Lathrup Village",
    state: "MI",
    zipCode: "48076",
    coordinates: { lat: 42.4972, lng: -83.2237 },
    propertyType: "single_family",
    price: 334000,
    sqft: 2010,
    bedrooms: 3,
    bathrooms: 2.5,
    lotSqft: 8712,
    sourceUrl: "https://example.com/listings/lh-001",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-mls" }
  },
  {
    id: "bf-001",
    provider: "mock-redfin",
    address: "18055 Hamilton Rd",
    city: "Beverly Hills",
    state: "MI",
    zipCode: "48025",
    coordinates: { lat: 42.5234, lng: -83.2328 },
    propertyType: "single_family",
    price: 529000,
    sqft: 2480,
    bedrooms: 4,
    bathrooms: 3,
    lotSqft: 12196,
    sourceUrl: "https://example.com/listings/bf-001",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-redfin" }
  },
  {
    id: "nv-001",
    provider: "mock-mls",
    address: "24521 Olde Orchard St",
    city: "Novi",
    state: "MI",
    zipCode: "48375",
    coordinates: { lat: 42.4617, lng: -83.4718 },
    propertyType: "condo",
    price: 289000,
    sqft: 1620,
    bedrooms: 3,
    bathrooms: 2.5,
    lotSqft: null,
    sourceUrl: "https://example.com/listings/nv-001",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-mls" }
  },
  {
    id: "nv-002",
    provider: "mock-realtor",
    address: "41922 Cherry Hill Rd",
    city: "Novi",
    state: "MI",
    zipCode: "48375",
    coordinates: { lat: 42.4706, lng: -83.4585 },
    propertyType: "single_family",
    price: 484000,
    sqft: 2680,
    bedrooms: 4,
    bathrooms: 3,
    lotSqft: 10454,
    sourceUrl: "https://example.com/listings/nv-002",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-realtor" }
  },
  {
    id: "nv-003",
    provider: "mock-redfin",
    address: "22234 Peachtree",
    city: "Novi",
    state: "MI",
    zipCode: "48375",
    coordinates: { lat: 42.4924, lng: -83.4691 },
    propertyType: "townhome",
    price: 355000,
    sqft: 1980,
    bedrooms: 3,
    bathrooms: 2.5,
    lotSqft: 3049,
    sourceUrl: "https://example.com/listings/nv-003",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-redfin" }
  },
  {
    id: "atx-001",
    provider: "mock-mls",
    address: "1902 Bluebonnet Ln",
    city: "Austin",
    state: "TX",
    zipCode: "78704",
    coordinates: { lat: 30.2486, lng: -97.7765 },
    propertyType: "single_family",
    price: 615000,
    sqft: 1930,
    bedrooms: 3,
    bathrooms: 2,
    lotSqft: 7040,
    sourceUrl: "https://example.com/listings/atx-001",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-mls" }
  },
  {
    id: "atx-002",
    provider: "mock-redfin",
    address: "3406 Clawson Rd",
    city: "Austin",
    state: "TX",
    zipCode: "78704",
    coordinates: { lat: 30.2272, lng: -97.7792 },
    propertyType: "townhome",
    price: 472000,
    sqft: 1780,
    bedrooms: 3,
    bathrooms: 2.5,
    lotSqft: 2178,
    sourceUrl: "https://example.com/listings/atx-002",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-redfin" }
  },
  {
    id: "atx-003",
    provider: "mock-realtor",
    address: "1117 Banister Ln Unit 201",
    city: "Austin",
    state: "TX",
    zipCode: "78704",
    coordinates: { lat: 30.2381, lng: -97.7831 },
    propertyType: "condo",
    price: 398000,
    sqft: 1310,
    bedrooms: 2,
    bathrooms: 2,
    lotSqft: null,
    sourceUrl: "https://example.com/listings/atx-003",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-realtor" }
  },
  {
    id: "atx-004",
    provider: "mock-mls",
    address: "4205 Clawson Rd",
    city: "Austin",
    state: "TX",
    zipCode: "78704",
    coordinates: { lat: 30.2234, lng: -97.7804 },
    propertyType: "single_family",
    price: 555000,
    sqft: 2240,
    bedrooms: 4,
    bathrooms: 3,
    lotSqft: 8120,
    sourceUrl: "https://example.com/listings/atx-004",
    createdAt: now,
    updatedAt: now,
    rawPayload: { source: "mock-mls" }
  }
];

export const MOCK_SAFETY: SafetyRecord[] = [
  { propertyId: "sf-001", crimeIndex: 28, schoolRating: 7.8, stabilityIndex: 71, source: "mock-safety", updatedAt: now },
  { propertyId: "sf-002", crimeIndex: 31, schoolRating: 8.1, stabilityIndex: 75, source: "mock-safety", updatedAt: now },
  { propertyId: "sf-003", crimeIndex: 35, schoolRating: 7.2, stabilityIndex: 66, source: "mock-safety", updatedAt: now },
  { propertyId: "sf-004", crimeIndex: 30, schoolRating: 7.5, stabilityIndex: 73, source: "mock-safety", updatedAt: now },
  { propertyId: "sf-005", crimeIndex: 27, schoolRating: 8.0, stabilityIndex: 74, source: "mock-safety", updatedAt: now },
  { propertyId: "sf-006", crimeIndex: 26, schoolRating: 8.3, stabilityIndex: 78, source: "mock-safety", updatedAt: now },
  { propertyId: "oak-001", crimeIndex: 39, schoolRating: 6.9, stabilityIndex: 61, source: "mock-safety", updatedAt: now },
  { propertyId: "oak-002", crimeIndex: 33, schoolRating: 7.1, stabilityIndex: 64, source: "mock-safety", updatedAt: now },
  { propertyId: "ro-001", crimeIndex: 22, schoolRating: 8.6, stabilityIndex: 81, source: "mock-safety", updatedAt: now },
  { propertyId: "lh-001", crimeIndex: 24, schoolRating: 8.4, stabilityIndex: 80, source: "mock-safety", updatedAt: now },
  { propertyId: "bf-001", crimeIndex: 19, schoolRating: 9.0, stabilityIndex: 86, source: "mock-safety", updatedAt: now },
  { propertyId: "nv-001", crimeIndex: 21, schoolRating: 8.8, stabilityIndex: 79, source: "mock-safety", updatedAt: now },
  { propertyId: "nv-002", crimeIndex: 18, schoolRating: 9.1, stabilityIndex: 87, source: "mock-safety", updatedAt: now },
  { propertyId: "nv-003", crimeIndex: 20, schoolRating: 8.7, stabilityIndex: 82, source: "mock-safety", updatedAt: now },
  { propertyId: "atx-001", crimeIndex: 41, schoolRating: 7.4, stabilityIndex: 68, source: "mock-safety", updatedAt: now },
  { propertyId: "atx-002", crimeIndex: 37, schoolRating: 7.0, stabilityIndex: 65, source: "mock-safety", updatedAt: now },
  { propertyId: "atx-003", crimeIndex: 42, schoolRating: 7.1, stabilityIndex: 62, source: "mock-safety", updatedAt: now },
  { propertyId: "atx-004", crimeIndex: 34, schoolRating: 7.9, stabilityIndex: 70, source: "mock-safety", updatedAt: now }
];
